version: "3"
services: 
  api:
    build: .
    ports: 
        - 7000:7000
    env_file:
      - ./.env
    environment:
        - DATABASE_HOSTNAME = localhost
        - DATABASE_PORT = 5433
        - DATABASE_NAME = fastapi
        - DATABASE_PASSWORD = pass123
        - DATABASE_USERNAME = postgres
        - SECRET_KEY = hello-world
        - ALGORITHM = HS256
        - ACCESS_TOKEN_EXPIRE_MINUTES = 30