"""add phone number

Revision ID: a65ba4f50212
Revises: b050e2271744
Create Date: 2023-11-24 16:27:27.115762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a65ba4f50212'
down_revision: Union[str, None] = 'b050e2271744'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phonenumber', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'users', ['phonenumber'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'phonenumber')
    # ### end Alembic commands ###
